services:
  nginx-proxy:
    image: nginxproxy/nginx-proxy
    container_name: nginx-proxy
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - /var/run/docker.sock:/tmp/docker.sock:ro
      - ./certs:/etc/nginx/certs:ro
      - ./vhost.d:/etc/nginx/vhost.d
      - ./html:/usr/share/nginx/html
    networks:
      - proxy-network
    restart: always

  letsencrypt:
    image: nginxproxy/acme-companion
    container_name: nginx-letsencrypt
    depends_on:
      - nginx-proxy
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - ./certs:/etc/nginx/certs:rw
      - ./vhost.d:/etc/nginx/vhost.d
      - ./html:/usr/share/nginx/html
    environment:
      - DEFAULT_EMAIL=andrey.surk.2904@gmail.com
    networks:
      - proxy-network
    restart: always

  whoami1:
    image: containous/whoami
    container_name: whoami1
    environment:
      - VIRTUAL_HOST=app1.andreysurk.ru
      - LETSENCRYPT_HOST=app1.andreysurk.ru
      - LETSENCRYPT_EMAIL=andrey.surk.2904@gmail.com
    networks:
      - proxy-network
    restart: always

  whoami2:
    image: containous/whoami
    container_name: whoami2
    environment:
      - VIRTUAL_HOST=app2.andreysurk.ru
      - LETSENCRYPT_HOST=app2.andreysurk.ru
      - LETSENCRYPT_EMAIL=andrey.surk.2904@gmail.com
    networks:
      - proxy-network
    restart: always

networks:
  proxy-network:
    driver: bridge